<a href="https://colab.research.google.com/github/navyagona/python-practice/blob/main/25_06_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **Introduction to Numpy**

 NumPy is a Python library that helps you work with numbers and data easily. It lets you create and use large lists of numbers (called arrays) and do math operations on them quickly. It's widely used for data analysis, science, and machine learning projects.

 ***advantages of numpy***


*   NumPy arrays use less memory as they store data more compactly compared to Python lists.
*  NumPy supports vectorized operations, allowing you to perform element-wise operations on entire arrays without writing loops.
*NumPy provides many built-in functions for mathematical operations, making it easier and faster to perform complex calculations.




In [1]:
import numpy as np
print(np.__version__)


1.25.2


NumPy Arrays

some commonly used numpy attributes:
1.shape:This attribute returns a tuple representing the dimensions of the array (number of rows and columns).

In [2]:
# 1D array
a = np.array([10, 20, 30, 40, 50])
print(a.shape)

# 2D array
b = np.array([[10, 20, 30], [40, 50, 60]])
print(b.shape)

# 3D array
c = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]]])
print(c.shape)

(5,)
(2, 3)
(2, 2, 2)


size: This attribute returns the total number of elements in the array.

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.size)

6


dtype: This attribute returns the data type of the elements in the array.

In [4]:
# Integer array
a = np.array([10, 20, 30, 40])
print(a.dtype)

# Float array
b = np.array([1.0, 2.0, 3.0])
print(b.dtype)

# Complex array
c = np.array([1+2j, 3+4j])
print(c.dtype)

# Boolean array
d = np.array([True, False, True])
print(d.dtype)

int64
float64
complex128
bool


commonly used functions to create arrays

np.array(): Create an array from a Python list or tuple.

In [6]:
import numpy as np
arr = np.array([1, 2, 3])


np.zeros(): Create an array of zeros with a specified shape.

In [7]:
zeros_arr = np.zeros((2, 3))


np.ones(): Create an array of ones with a specified shape.

In [8]:
ones_arr = np.ones((3, 2))  # Creates a 3x2 array of ones


np.full(): Create an array with a specified shape and fill it with a specified value.

In [9]:
full_arr = np.full((2, 2), 5)  # Creates a 2x2 array filled with 5


np.arange(): Create an array with evenly spaced values within a given interval.

In [10]:
arange_arr = np.arange(0, 10, 2)  # Creates array [0, 2, 4, 6, 8]


np.linspace(): Create an array with evenly spaced values over a specified interval.

In [11]:
linspace_arr = np.linspace(0, 1, 5)  # Creates array [0.  0.25  0.5  0.75  1.]


np.random.rand(): Create an array of specified shape with random values from a uniform distribution over [0, 1)

In [12]:
rand_arr = np.random.rand(2, 3)  # Creates a 2x3 array of random values


np.eye(): Create an identity matrix of a specified size.

In [13]:
eye_arr = np.eye(3)  # Creates a 3x3 identity matrix


np.empty(): Create an uninitialized array of specified shape and data type.

In [14]:
empty_arr = np.empty((2, 2))  # Creates a 2x2 array (initial contents are random)


Numpy Array operations and broadcasting

1.basic array operations:

addition:add two arrays


In [15]:
a = np.array([2, 4, 6])
b = np.array([4, 8, 10])

c = a + b
print(c)

[ 6 12 16]


subtraction:subtract two arrays

In [16]:
a = np.array([8, 9, 10])
b = np.array([4, 5, 6])

c = a - b
print(c)

[4 4 4]


multiplication:multiply two arrays

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
print(c)

[ 4 10 18]


division:divide two arrays

In [18]:
a = np.array([8, 10, 12])
b = np.array([4, 5, 6])

c = a / b
print(c)

[2. 2. 2.]


Scalar Operations: Multiplies/Divides each element of the array by the scalar value

In [19]:
a = np.array([2, 4, 6])

b = a * 2
print(b)

c = a / 2
print(c)

[ 4  8 12]
[1. 2. 3.]


Square Root(np.sqrt()): Computes the square root of each element in the array.

In [20]:
 a= np.array([1, 16, 25])

b = np.sqrt(a)
print(b)

[1. 4. 5.]


Exponential(np.exp()): Computes the exponential of each element in the array.

In [21]:
a = np.array([4, 5, 6])

b = np.exp(a)
print(b)

[ 54.59815003 148.4131591  403.42879349]


BROADCASTING:

In [22]:
import numpy as np

# Create an array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Add a scalar to each element of the array
result = arr + 10
print(result)
# Output:
# [[11 12 13]
#  [14 15 16]]


[[11 12 13]
 [14 15 16]]


In [23]:
import numpy as np

# Create two arrays of different shapes
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])

# Add arrays with different shapes
C = A + B
print(C)
# Output:
# [[11 22 33]
#  [14 25 36]]


[[11 22 33]
 [14 25 36]]


In [24]:
import numpy as np

# Create two arrays of different shapes
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[10], [20]])

# Add arrays with different shapes
C = A + B
print(C)
# Output:
# [[11 12 13]
#  [24 25 26]]


[[11 12 13]
 [24 25 26]]


In [25]:
import numpy as np

# Create two arrays of different shapes
A = np.array([1, 2, 3])  # Shape: (3,)
B = 10  # Scalar

# Multiply each element of A by scalar B
C = A * B
print(C)  # Output: [10 20 30]


[10 20 30]


Element-wise Operations And Their Efficiency

In [27]:
import numpy as np
import time

# Create two large arrays
size = 1000000
A = np.random.rand(size)
B = np.random.rand(size)

# Perform element-wise addition using NumPy
start_time = time.time()
C = A + B
numpy_time = time.time() - start_time

# Perform element-wise addition using Python loops
start_time = time.time()
D = []
for i in range(size):
    D.append(A[i] + B[i])
python_time = time.time() - start_time

# Compare the execution times
print(f"NumPy execution time: {numpy_time} seconds")
print(f"Python loop execution time: {python_time} seconds")
print(f"NumPy is {python_time / numpy_time:.2f} times faster than Python loops for this operation.")


NumPy execution time: 0.006707429885864258 seconds
Python loop execution time: 0.45642542839050293 seconds
NumPy is 68.05 times faster than Python loops for this operation.


indexing and slicing:

In [28]:
import numpy as np

# Create a 2D NumPy array (matrix)
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Indexing to access specific elements
print("Element at row 0, column 1:", arr[0, 1])  # Output: 2
print("Element at row 2, column 3:", arr[2, 3])  # Output: 12

# Slicing to extract subarrays
print("First row:", arr[0])  # Output: [1 2 3 4]
print("First column:", arr[:, 0])  # Output: [1 5 9]

# Slicing a subarray
print("Subarray from row 1 to 2, and column 1 to 3:")
print(arr[1:3, 1:4])
# Output:
# [[ 6  7  8]
#  [10 11 12]]


Element at row 0, column 1: 2
Element at row 2, column 3: 12
First row: [1 2 3 4]
First column: [1 5 9]
Subarray from row 1 to 2, and column 1 to 3:
[[ 6  7  8]
 [10 11 12]]


ARRAY MANIPULATION:
1.reshaping arrays:

In [29]:
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape into a 2D array (3 rows, 2 columns)
arr2d = arr1d.reshape(3, 2)
print("Reshaped 2D array:")
print(arr2d)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]

# Flatten the array back to 1D
flattened_arr = arr2d.flatten()
print("Flattened 1D array:")
print(flattened_arr)
# Output: [1 2 3 4 5 6]


Reshaped 2D array:
[[1 2]
 [3 4]
 [5 6]]
Flattened 1D array:
[1 2 3 4 5 6]


concateation

In [30]:
import numpy as np

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Concatenate along axis 0 (rows)
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenated array along axis 0:")
print(concatenated_arr)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]


Concatenated array along axis 0:
[[1 2]
 [3 4]
 [5 6]]


splitting arrays

In [31]:
import numpy as np

# Create an array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Split the array into 2 subarrays along axis 0
subarrays = np.split(arr, 2, axis=0)
print("Split array along axis 0:")
print(subarrays)
# Output:
# [array([[1, 2, 3],
#         [4, 5, 6]]),
#  array([[ 7,  8,  9],
#         [10, 11, 12]])]

# Split the array into 3 subarrays along axis 1
subarrays_axis1 = np.split(arr, 3, axis=1)
print("Split array along axis 1:")
print(subarrays_axis1)
# Output:
# [array([[ 1],
#         [ 4],
#         [ 7],
#         [10]]),
#  array([[ 2],
#         [ 5],
#         [ 8],
#         [11]]),
#  array([[ 3],
#         [ 6],
#         [ 9],
#         [12]])]


Split array along axis 0:
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
Split array along axis 1:
[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


transposing arrays

In [32]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the array
transposed_arr = np.transpose(arr)
print("Transposed array:")
print(transposed_arr)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]


Transposed array:
[[1 4]
 [2 5]
 [3 6]]


stacking arrays

In [33]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack arrays vertically (along axis 0)
stacked_vertically = np.vstack((arr1, arr2))
print("Vertically stacked array:")
print(stacked_vertically)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Stack arrays horizontally (along axis 1)
stacked_horizontally = np.hstack((arr1.reshape(-1, 1), arr2.reshape(-1, 1)))
print("Horizontally stacked array:")
print(stacked_horizontally)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]


Vertically stacked array:
[[1 2 3]
 [4 5 6]]
Horizontally stacked array:
[[1 4]
 [2 5]
 [3 6]]


stacking and splitting of arrays

In [34]:
import numpy as np

# Create two arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Stack arrays vertically (along axis 0)
stacked_vertically = np.vstack((arr1, arr2))
print("Vertically stacked array:")
print(stacked_vertically)
# Output:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]

# Split the vertically stacked array into 2 subarrays along axis 0
subarrays = np.split(stacked_vertically, 2, axis=0)
print("\nSplit vertically stacked array along axis 0:")
print(subarrays)
# Output:
# [array([[1, 2, 3],
#         [4, 5, 6]]),
#  array([[ 7,  8,  9],
#         [10, 11, 12]])]

# Stack arrays horizontally (along axis 1)
stacked_horizontally = np.hstack((arr1, arr2))
print("\nHorizontally stacked array:")
print(stacked_horizontally)
# Output:
# [[ 1  2  3  7  8  9]
#  [ 4  5  6 10 11 12]]

# Split the horizontally stacked array into 2 subarrays along axis 1
subarrays_axis1 = np.split(stacked_horizontally, 2, axis=1)
print("\nSplit horizontally stacked array along axis 1:")
print(subarrays_axis1)
# Output:
# [array([[1, 2, 3],
#         [4, 5, 6]]),
#  array([[ 7,  8,  9],
#         [10, 11, 12]])]


Vertically stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Split vertically stacked array along axis 0:
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]

Horizontally stacked array:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Split horizontally stacked array along axis 1:
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


methods for adding and removing elements

1.Appending Elements

In [35]:
import numpy as np

# Example of appending elements
arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5, 6])
print("Appended array:", new_arr)
# Output: [1 2 3 4 5 6]


Appended array: [1 2 3 4 5 6]


2.Inserting Elements

In [36]:
import numpy as np

# Example of inserting elements
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.insert(arr, 2, [6, 7])
print("Inserted array:", new_arr)
# Output: [1 2 6 7 3 4 5]


Inserted array: [1 2 6 7 3 4 5]


3.Deleting Elements

In [37]:
import numpy as np

# Example of deleting elements
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.delete(arr, 2)
print("Deleted array:", new_arr)
# Output: [1 2 4 5]


Deleted array: [1 2 4 5]


4.Trimming Elements

In [38]:
import numpy as np

# Example of trimming elements
arr = np.array([1, 2, 3, 4, 5])
new_arr = arr[:-2]  # Keep all elements except the last two
print("Trimmed array:", new_arr)
# Output: [1 2 3]


Trimmed array: [1 2 3]
